### ISSUE TITLE
创建jobflow无法正常运行

### ISSUE THREAD

**Issue by zxyyzx** [BoCloud/JobFlow#5]
你好，我在搭建好的集群尝试使用jobflow
jobtemplate.yaml如下：
```
apiVersion: batch.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: a
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: default
  policies:
    - event: PodEvicted
      action: RestartJob
  maxRetry: 5
  queue: default

  tasks:
    - replicas: 1
      name: "test-task"
      policies: 
        - event: TaskCompleted
          action: CompletedJob
      template:
        metadata:
          name: test-task
        spec:
          containers:
            - name: test
              image: centos
              imagePullPolicy: IfNotPresent
              command: ["/bin/bash", "-c"]
              args: ["touch /home/a.txt && echo 'this is test string' >> /home/a.txt && sleep 10 "]
              resources:
                requests:
                  cpu: "1"
              volumeMounts:
                - mountPath: /home
                  name: my-pvc
          volumes:
          - name: my-pvc
            persistentVolumeClaim:
              claimName: my-pvc-test
---
apiVersion: batch.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: b
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: default
  policies:
    - event: PodEvicted
      action: RestartJob
  maxRetry: 5
  queue: default

  tasks:
    - replicas: 1
      name: "test-task"
      policies: 
        - event: TaskCompleted
          action: CompletedJob
      template:
        metadata:
          name: test-task
        spec:
          containers:
            - name: test
              image: centos
              imagePullPolicy: IfNotPresent
              command: ["/bin/bash", "-c"]
              args: ["touch /home/b.txt && echo 'this is test string' >> /home/b.txt && sleep 10 "]
              resources:
                requests:
                  cpu: "1"
              volumeMounts:
                - mountPath: /home
                  name: my-pvc
          volumes:
          - name: my-pvc
            persistentVolumeClaim:
              claimName: my-pvc-test
---
```
job flow.yaml如下：
```
apiVersion: batch.volcano.sh/v1alpha1
kind: JobFlow
metadata:
  name: test
  namespace: default
spec:
  jobRetainPolicy: retain   # After jobflow runs, keep the generated job. Otherwise, delete it.
  flows:
    - name: a
    - name: b
      dependsOn:
        targets: ['a']
```

我现在面临的问题是，create jobtemplate后create jobflow，执行 kubectl get jf，存在的jf无状态信息显示，如下：
```
NAME   STATUS   AGE
test            10m
```
执行kubectl get pods ，也未见pod被创建。
